# 语音角色id，可在对话中指定角色，不指定则为使用默认角色（派蒙 430）
character_id: 430
# 是否为每个用户默认开启语音功能，默认为False，即不开启，True为默认开启
voice_switch: False
# 语音传输方式：path/base64，如果遇到消息平台访问权限问题，可尝试切换
voice_type: path
# 语音缓存路径，如果遇到消息平台访问权限问题，可以尝试修改至消息平台有权限访问的目录
temp_dir_path: plugins/NewChatVoice/audio_temp
# token，这个是必须的，不然无法使用，获取方式请看文档
token: 填入购买后显示的网站